blank_issues_enabled: false
contact_links:
  - name: â“ Questions, Help, and Advice
    url: https://github.com/tubitak-bilgem-yte/yakut-ui/discussions
    about: For general support, please refer to the Material Web discussion board.